//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dburunEntities : DbContext
    {
        public dburunEntities()
            : base("name=dburunEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbladmin> tbladmin { get; set; }
        public virtual DbSet<tblkatogori> tblkatogori { get; set; }
        public virtual DbSet<tblmusteri> tblmusteri { get; set; }
        public virtual DbSet<tblsatislar> tblsatislar { get; set; }
        public virtual DbSet<tblstoklar> tblstoklar { get; set; }
        public virtual DbSet<tblurunler> tblurunler { get; set; }
    }
}
